config/routes.rb
Rails.application.routes.draw do
  
  resources :towers do 
    resources :apartaments do 
      resources :people     
    end
  end

end

app/models/apartament.rb
class Apartament < ActiveRecord::Base
	validates_presence_of :nombre , :piso
	belongs_to :tower
	has_many :people
end

app/models/person.rb
class Person < ActiveRecord::Base
	validates_presence_of :nombre, :identificacion
	belongs_to :apartament
end

app/models/tower.rb
class Tower < ActiveRecord::Base
	validates_presence_of :nombre , :portero
	has_many :apartaments
end

app/controllers/apartaments_controller.rb
class ApartamentsController < ApplicationController
	def index
		@apartaments = Apartament.all
	end

	def new
		@tower = Tower.find(params[:tower_id])
		@apartament = @tower.apartaments.new
	end
	def create
		@tower = Tower.find(params[:tower_id])
		apartament = @tower.apartaments.new(apartament_params)
		apartament.save
		redirect_to tower_path(@tower)
	end
	def edit
		@tower = Tower.find(params[:tower_id])
		@apartament = @tower.apartaments.find(params[:id])
	end
	def update
		@tower = Tower.find(params[:tower_id])
		@apartament = @tower.apartaments.find(params[:id])
		@apartament.update(apartament_params)
		redirect_to tower_path(@tower)
	end
	def destroy
		@tower= Tower.find(params[:tower_id])
		@apartament = @tower.apartaments.find(params[:id])
		@apartament.destroy
		redirect_to tower_path(@tower)
	end
	def show
		@tower = Tower.find(params[:tower_id])
		@apartament = @tower.apartaments.find(params[:id])
		@people = @apartament.people.all
	end

	private
	def apartament_params
		params.require(:apartament).permit(:nombre, :piso ,:tower_id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  	@people = Person.all
  end
  def new
  	@tower = Tower.find(params[:tower_id])
  	@apartament = @tower.apartaments.find(params[:apartament_id])
	 @person= @apartament.people.new
  end
  def create
		@tower = Tower.find(params[:tower_id])
		@apartament = @tower.apartaments.find(params[:apartament_id])
		person = @apartament.people.new(person_params)
		person.save
		redirect_to tower_apartament_path(@tower,@apartament)
	end

  def edit
    @tower = Tower.find(params[:tower_id])
    @apartament = @tower.apartaments.find(params[:apartament_id])
    @person = @apartament.people.find(params[:id])
  end
  def update
    @tower = Tower.find(params[:tower_id])
    @apartament = @tower.apartaments.find(params[:apartament_id])
    @person = @apartament.people.find(params[:id])
    @person.update(person_params)
    redirect_to tower_apartament_path(@tower,@apartament)
  end
  def destroy
    @tower= Tower.find(params[:tower_id])
    @apartament = @tower.apartaments.find(params[:apartament_id])
    @person = @apartament.people.find(params[:id])
    @person.destroy
    redirect_to tower_apartament_path(@tower,@apartament)
  end

  def show
  end
  private
  def person_params
    params.require(:person).permit(:nombre , :identificacion , :apartament_id)
  end
end

app/controllers/towers_controller.rb
class TowersController < ApplicationController
  def index
  	@towers = Tower.all
  end

  def new
  	@tower = Tower.new
  end
  def create
  	@tower = Tower.new(tower_params)
  	@tower.save
  	redirect_to towers_path

  end

  def show
  	@tower = Tower.find(params[:id])
  	@apartaments = @tower.apartaments.all
  end

  def edit
  	@tower= Tower.find(params[:id])
  end
  def update
  	@tower = Tower.find(params[:id])
  	@tower.update(tower_params)
  	redirect_to towers_path
  end
  def destroy
  	@tower = Tower.find(params[:id])
  	@tower.destroy
  	redirect_to towers_path
  end
  private
  def tower_params
	params.require(:tower).permit(:nombre , :portero)  	
  end
end

app/helpers/apartaments_helper.rb
module ApartamentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/views/apartaments/_form.html.erb
<div class="container">
<%= form_for [@tower,@apartament] do |f| %>

<div class="field">
	<%= f.label :nombre, "Numero apartamento: " %>
	<%= f.text_field :nombre %>
</div>

<div class="field">
	<%= f.label :piso %>
	<%= f.text_field :piso %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>
</div>

app/views/apartaments/edit.html.erb
<h1 class="center">Editar Apartamento</h1>
<%= render 'form' %>

app/views/apartaments/index.html.erb
<h1>Apartaments#index</h1>
<p>Find me in app/views/apartaments/index.html.erb</p>

app/views/apartaments/new.html.erb
<h1>Nuevo apartamento </h1>
<%= render 'form' %>

app/views/apartaments/show.html.erb
<h2 class="center ">Apartament: <%= @apartament.nombre %></h2>
<h3 class= "center">Piso: <%= @apartament.piso %></h3>
<%= link_to raw("<i class='material-icons'>add</i>") , new_tower_apartament_person_path(@tower,@apartament) , :class => "btn-floating btn-light waves-effect waves-light blue" %>
<table>
	
	<thead>
	<th>Nombre </th>
	<th>identificacion</th>
	</thead>
 <tbody>
 	<% @people.each do |a| %>  
	<tr>
		<td><%= a.nombre %> </td>
		<td><%= a.identificacion %></td>
		<td> <%= link_to raw("<i class='material-icons'>mode_edit</i>"), edit_tower_apartament_person_path(@tower,@apartament,a) %> </td>
		<td><%= link_to raw("<i class='material-icons '>delete</i> " ), tower_apartament_person_path(@tower,@apartament,a), method: :delete, data: {confirm: "Estas
Seguro"} %></td>

	</tr>
 	<% end %>
 </tbody>
</table>
<%=link_to "Volver a apartamentos", tower_path(@tower) , :class => "left btn waves-effect waves-light blue"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppAptos</title>
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/people/_form.html.erb
<div class="container">
<%= form_for [@tower,@apartament,@person] do |f| %>

<div class="field">
	<%= f.label :nombre %>
	<%= f.text_field :nombre %>
</div>

<div class="field">
	<%= f.label :identificacion %>
	<%= f.text_field :identificacion %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>
</div>

app/views/people/edit.html.erb
<h1 class="center">Editar persona</h1>
<%= render 'form' %>

app/views/people/index.html.erb
<h1>People#index</h1>

app/views/people/new.html.erb
<h1 class="center">Crear apartamento</h1>
<%= render 'form' %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>

app/views/towers/_form.html.erb
<div class="container">
	<%= form_for @tower do |t| %>
	<div class="field">
			<%= t.label :nombre %>
			<%= t.text_field :nombre %>
	</div>

	<div class="field">
		<%= t.label :portero %>
		<%= t.text_field :portero %>
	</div>

	<div class="actions">
		<%= t.submit %>
	
 	<% end %>
 	</div>

</div>

app/views/towers/edit.html.erb
<h1>Editar Torre</h1>
<%= render 'form' %>

app/views/towers/index.html.erb
<h1>Lista de Torres</h1>
<%= link_to raw("<i class='material-icons'>add</i>") , new_tower_path, :class => "btn-floating btn-light waves-effect waves-light blue" %>

<table>
	<thead>

		<th>Nombre </th>
		<th>Portero</th>
		<th>Aptos</th>

	</thead>
	<% @towers.each do |t|  %>
	<tbody>
		<tr>
			<td><%=t.nombre%></td>
			<td><%= t.portero %></td>
			<td><%= t.apartaments.count %></td>
			<td><%=link_to raw("<i class='material-icons'>mode_edit</i>"), edit_tower_path(t)%></td>
			<td><%= link_to raw("<i class='material-icons '>delete</i> " ), tower_path(t), method: :delete, data: {confirm: "Estas
Seguro"} %></td> <td><%=link_to raw("<i class='material-icons right'>info</i>apartamentos " ), t,:class => "btn waves-effect waves-light blue" %>
</td>
		</tr>
	
	<% end %>
</tbody>
</table>

app/views/towers/new.html.erb
<h1>Crear torres</h1>
<%= render 'form' %>

app/views/towers/show.html.erb
<h1 class="center"> <%= @tower.nombre.upcase %></h1>
<h3 class= "center">  <b> Portero: </b><%= @tower.portero.capitalize %></h3>
 <%= link_to raw("<i class='material-icons'>add</i>"), new_tower_apartament_path(@tower), :class => "btn-floating btn-light waves-effect waves-light blue"  %>  

<table>
	
	<thead>
	<th>Apartamento </th>
	<th>Piso</th>
	<th>Personas</th>
	</thead>
 <tbody>
 	<% @apartaments.each do |a| %>  
	<tr>
		<td><%= a.nombre %> </td>
		<td><%= a.piso %></td>
		<td><%= a.people.count %></td>
		<td> <%= link_to raw("<i class='material-icons'>mode_edit</i>"), edit_tower_apartament_path(@tower,a) %> </td>
		<td><%= link_to raw("<i class='material-icons '>delete</i> " ), tower_apartament_path(@tower,a), method: :delete, data: {confirm: "Estas
Seguro"} %></td> <td><%= link_to raw("<i class='material-icons right'>info</i> personas" ),tower_apartament_path(@tower,a), :class => "btn waves-effect waves-light blue"  %></td>

	</tr>
 	<% end %>
 </tbody>
</table>

<%=link_to "Volver a Torres", towers_path , :class => "left btn waves-effect waves-light blue"%>